name: Get static analysis tools configs.
description: This action gets the required configs for the static analysis tools used to check nri-integrations.
inputs:
  semgrep-append:
    description: If set to true, local semgrep file policies will join the ones in this repository.
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y
        yq --version
      shell: bash
    - run: $GITHUB_ACTION_PATH/action.sh
      shell: bash
      env:
        SEMGREP_APPEND: ${{ inputs.semgrep-append }}
